config/routes.rb
Abogadosrpr::Application.routes.draw do

  resources :preguntas

  resources :contactos

  resources :documentos

  get "inicios/index"

  get "inicios"=>"inicios#index"

  resources :fotos

  resources :paginas

  resources :notices

  root :to => 'inicios#index'

end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
  attr_accessible :descripcion, :titulo
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  # GET /paginas
  # GET /paginas.json
  def index
    @paginas = Pagina.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paginas }
    end
  end

  # GET /paginas/1
  # GET /paginas/1.json
  def show
    @pagina = Pagina.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pagina }
    end
  end

  # GET /paginas/new
  # GET /paginas/new.json
  def new
    @pagina = Pagina.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pagina }
    end
  end

  # GET /paginas/1/edit
  def edit
    @pagina = Pagina.find(params[:id])
  end

  # POST /paginas
  # POST /paginas.json
  def create
    @pagina = Pagina.new(params[:pagina])

    respond_to do |format|
      if @pagina.save
        format.html { redirect_to @pagina, notice: 'Pagina was successfully created.' }
        format.json { render json: @pagina, status: :created, location: @pagina }
      else
        format.html { render action: "new" }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paginas/1
  # PUT /paginas/1.json
  def update
    @pagina = Pagina.find(params[:id])

    respond_to do |format|
      if @pagina.update_attributes(params[:pagina])
        format.html { redirect_to @pagina, notice: 'Pagina was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paginas/1
  # DELETE /paginas/1.json
  def destroy
    @pagina = Pagina.find(params[:id])
    @pagina.destroy

    respond_to do |format|
      format.html { redirect_to paginas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/paginas/_form.html.erb
<%= form_for(@pagina) do |f| %>
  <% if @pagina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pagina.errors.count, "error") %> prohibited this pagina from being saved:</h2>

      <ul>
      <% @pagina.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paginas/edit.html.erb
<h1>Editing pagina</h1>

<%= render 'form' %>

<%= link_to 'Show', @pagina %> |
<%= link_to 'Back', paginas_path %>

app/views/paginas/index.html.erb
<h1>Listing paginas</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paginas.each do |pagina| %>
  <tr>
    <td><%= pagina.titulo %></td>
    <td><%= pagina.descripcion %></td>
    <td><%= link_to 'Show', pagina %></td>
    <td><%= link_to 'Edit', edit_pagina_path(pagina) %></td>
    <td><%= link_to 'Destroy', pagina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pagina', new_pagina_path %>

app/views/paginas/new.html.erb
<h1>New pagina</h1>

<%= render 'form' %>

<%= link_to 'Back', paginas_path %>

app/views/paginas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @pagina.titulo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @pagina.descripcion %>
</p>


<%= link_to 'Edit', edit_pagina_path(@pagina) %> |
<%= link_to 'Back', paginas_path %>