config/routes.rb
Abogadosrpr::Application.routes.draw do

  resources :preguntas

  resources :contactos

  resources :documentos

  get "inicios/index"

  get "inicios"=>"inicios#index"

  resources :fotos

  resources :paginas

  resources :notices

  root :to => 'inicios#index'

end

app/models/pregunta.rb
class Pregunta < ActiveRecord::Base
  attr_accessible :contenido, :titulo

	#def self.search(search)
	 # 	if search
	 #   	find(:all, :conditions => ['titulo LIKE ?', "%#{search}%"])
	 # 	else
	 #   	find(:all)
	 # 	end
	#end

	def self.search(search)
  		where do  			
        	titulo =~ "%#{search}%"
  		end
	end

end

app/controllers/preguntas_controller.rb
class PreguntasController < ApplicationController
  # GET /preguntas
  # GET /preguntas.json
  def index
    #@preguntas = Pregunta.where{{titulo => "eres soltero"}}

    @preguntas = Pregunta.search(params[:search])
    @idp        = @preguntas[0]['id']
    @titulo     = @preguntas[0]['titulo']
    @contenido  = @preguntas[0]['contenido']


    #@preguntas = Pregunta.all   
  end

  # GET /preguntas/1
  # GET /preguntas/1.json
  def show
    @pregunta = Pregunta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pregunta }
    end
  end

  # GET /preguntas/new
  # GET /preguntas/new.json
  def new
    @pregunta = Pregunta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pregunta }
    end
  end

  # GET /preguntas/1/edit
  def edit
    @pregunta = Pregunta.find(params[:id])
  end

  # POST /preguntas
  # POST /preguntas.json
  def create
    @pregunta = Pregunta.new(params[:pregunta])

    respond_to do |format|
      if @pregunta.save
        format.html { redirect_to @pregunta, notice: 'Pregunta was successfully created.' }
        format.json { render json: @pregunta, status: :created, location: @pregunta }
      else
        format.html { render action: "new" }
        format.json { render json: @pregunta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /preguntas/1
  # PUT /preguntas/1.json
  def update
    @pregunta = Pregunta.find(params[:id])

    respond_to do |format|
      if @pregunta.update_attributes(params[:pregunta])
        format.html { redirect_to @pregunta, notice: 'Pregunta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pregunta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preguntas/1
  # DELETE /preguntas/1.json
  def destroy
    @pregunta = Pregunta.find(params[:id])
    @pregunta.destroy

    respond_to do |format|
      format.html { redirect_to preguntas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/preguntas_helper.rb
module PreguntasHelper
end

app/views/preguntas/_form.html.erb
<%= form_for(@pregunta) do |f| %>
  <% if @pregunta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pregunta.errors.count, "error") %> prohibited this pregunta from being saved:</h2>

      <ul>
      <% @pregunta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_area :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preguntas/edit.html.erb
<h1>Editing pregunta</h1>

<%= render 'form' %>

<%= link_to 'Show', @pregunta %> |
<%= link_to 'Back', preguntas_path %>

app/views/preguntas/index.html.erb
<div class="jumbotron subhead">
  <div class="container">
    <h1>Preguntas</h1>
    <p class="lead">Inteligencia Artificial de Preguntas</p>
  </div>
</div>

<div class="container">

  <div class="row">
    <div class="span8">


      <!-- INTELIGENCIA ARTIFICIAL
      =================================================-->
      <section>
        <div class="page-header">
          <h1>Inteligencia A. <small> Ing Edgar Taya</small></h1>          
        </div>        
        <div class="well">
          <div class="row-fluid">
            <div class="span4">
              <%= image_tag "user_icon2.jpg" %>
            </div>
            <div class="span8">
              <%= form_for(preguntas_path, :method => "get") do |f| %>
                <%= text_field_tag :search, params[:search] %>                
              <% end %>
              <h2>¿<%= @titulo %> ?</h2>
              <p class="lead"><%= @contenido %></p>              
            </div>
          </div>                    
        </div>
        <div class="well">
          <%= link_to raw('<i class="icon-home icon-white"></i> Home'), preguntas_path, :class=>"btn btn-primary"  %>
          <%= link_to raw('<i class="icon-lock"></i> Nueva'), new_pregunta_path, :class=> "btn" %>
          <%= link_to raw('<i class="icon-edit"></i> Editar'), "/preguntas/#{@idp}/edit", :class=>"btn" %>
          </div>
      </section>

    
    </div>
    <div class="span4">


      <!-- Informacion Abogados RpR 
        ===============================================   -->
        <section>
          <div class="page-header">
            <h1>Informacion</h1>
          </div>
          <table class="table table-bordered table-condensed">
            <tr>
              <td>
                <%= image_tag "rolando_portada2.png" %>
              </td>
            </tr>             
            <tr>
              <td>                   
                <dt>Nombre y Profesion</dt>
                  <dd>Rolando J Prado Reyes</dd>                    
                  <dd>ABOGADO</dd>
              </td>
            </tr>               
            <tr>
              <td>
                <dt>Correos</dt>
                <dd>Abogadostacna@gmail.com</dd>
                <dd>rolandoprado2009@hotmail.com</dd>
              </td>
            </tr>
            <tr>
              <td>
                <dt>Telefonos</dt>
                <dd>RPM #976557200</dd>
                <dd>RPC 946692854</dd>
                <dd>Nextel 99 835*9404</dd>
                <dd>fono 411616</dd>
              </td>
            </tr>
          </table>          
        </section>
    </div>
  </div>



</div>

app/views/preguntas/new.html.erb
<h1>New pregunta</h1>

<%= render 'form' %>

<%= link_to 'Back', preguntas_path %>

app/views/preguntas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @pregunta.titulo %>
</p>

<p>
  <b>Contenido:</b>
  <%= @pregunta.contenido %>
</p>


<%= link_to 'Edit', edit_pregunta_path(@pregunta) %> |
<%= link_to 'Back', preguntas_path %>